name: Go Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  
jobs:
    runs-on: ubuntu-latest

  Setup:
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
  
  Build:
    steps:
    - name: Build
      run: go build -v ./...

  Test:
    steps:
    - name: Test
      run: go test -v ./...
