name: Go Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  
jobs:
  go-build-and-test-job:
    name: Go build and test job
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout step
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
  
      - name: Build Step
        run: go build -v ./...

      - name: Get gotestsum tooling
        run: go install gotest.tools/gotestsum@latest

      - name: Run gotestsum to generate JUnit XML file
        run: gotestsum --junitfile unit-tests.xml

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Go Test Results            # Name of the check run which will be created
          path: ./unit-tests.xml    # Path to test results
          reporter: java-junit        # Format of test results
          