name: Go Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  
jobs:
  go-build-and-test-job:
    name: Go build and test job
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout step
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
  
      - name: Build Step
        run: go build -v ./...

      - name: Test Step
        run: go test -v ./...
